FROM debian:buster

RUN apt-get update \
 && apt-get install -y sqlite3 libsqlite3-dev

COPY ./target/release/scum_bot /opt/scum-bot/bin/scum_bot

ADD ./config/sql/* /opt/scum-bot/share/sql/

ADD ./config/bin/* /opt/scum-bot/bin/

CMD ["/opt/scum-bot/bin/entrypoint.sh"]
