version: '3.3'
services:
  scum-bot:
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
    - DATABASE_PATH=/opt/scum-bot/var/data/scum-bot.db
    - DISCORD_TOKEN
    - MODEL_PATH=/opt/scum-bot/share/model
    - RUST_LOG=scum-bot=INFO
    volumes:
    - ${PWD}/model/:/opt/scum-bot/share/model/
    - ${PWD}/data/:/opt/scum-bot/var/data/
